FROM google/golang:latest
MAINTAINER Arthur Shui <shuiyuzhe@gmail.com>

# install depencies
RUN go get github.com/astaxie/beego
RUN go get labix.org/v2/mgo
RUN go get github.com/chanxuehong/wechat
RUN go get github.com/magicshui/goutils
RUN go get github.com/magicshui/pm-sdk-curio-api
RUN go get github.com/qiniu/api


CMD ["/bin/bash"]


